version: '3.8'

secrets:
  webhook:
    file: ./webhook.secret

services:
  webhook:
    build: .
    container_name: webhook
    secrets:
      - webhook
    environment:
      WEBHOOK_SECRET_FILE: /run/secrets/webhook
      # WEBHOOK_SECRET: ${WEBHOOK_SECRET:?WEBHOOK_SECRET is required!}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./logs:/home/logs
    ports:
      - 8000:8000
